<a href="https://colab.research.google.com/github/yashpokra/Financial-Sentiment-Analysis/blob/main/Finance_Sentiment_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import random 

In [ ]:
#Downloading dataset file from github
!wget https://raw.githubusercontent.com/yashpokra/Financial-Sentiment-Analysis/main/financial%20-%20sentiment%20analysis.csv


--2022-04-25 20:26:08--  https://raw.githubusercontent.com/yashpokra/Financial-Sentiment-Analysis/main/financial%20-%20sentiment%20analysis.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 745117 (728K) [text/plain]
Saving to: ‘financial - sentiment analysis.csv’

financial - sentime 100%[===================>] 727.65K  --.-KB/s    in 0.03s   

2022-04-25 20:26:08 (27.1 MB/s) - ‘financial - sentiment analysis.csv’ saved [745117/745117]



In [ ]:
# Creating a data frame 
finance_dataset = pd.read_csv("/content/financial - sentiment analysis.csv")

In [ ]:
finance_dataset.head(10) # checking the first 10 rows 

Sentence Sentiment
0  The GeoSolutions technology will leverage Bene...  positive
1  $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2  For the last quarter of 2010 , Componenta 's n...  positive
3  According to the Finnish-Russian Chamber of Co...   neutral
4  The Swedish buyout firm has sold its remaining...   neutral
5    $SPY wouldn't be surprised to see a green close  positive
6  Shell's $70 Billion BG Deal Meets Shareholder ...  negative
7  SSH COMMUNICATIONS SECURITY CORP STOCK EXCHANG...  negative
8  Kone 's net sales rose by some 14 % year-on-ye...  positive
9  The Stockmann department store will have a tot...   neutral

Converting the Sentiment labels into numerical form, so that we can develop a multiclass problem, where:

`negative` = 0

`neutral` = 1 

`positive` = 2

In [ ]:
dataset_dict = {"negative": 0, "neutral": 1, "positive":2} # Creating dictionary 
finance_dataset["Sentiment"].replace(dataset_dict, inplace = True) # set inplace to True, so that it will directly the modify the changes to the dataframe directly
finance_dataset.head(10)

Sentence  Sentiment
0  The GeoSolutions technology will leverage Bene...          2
1  $ESI on lows, down $1.50 to $2.50 BK a real po...          0
2  For the last quarter of 2010 , Componenta 's n...          2
3  According to the Finnish-Russian Chamber of Co...          1
4  The Swedish buyout firm has sold its remaining...          1
5    $SPY wouldn't be surprised to see a green close          2
6  Shell's $70 Billion BG Deal Meets Shareholder ...          0
7  SSH COMMUNICATIONS SECURITY CORP STOCK EXCHANG...          0
8  Kone 's net sales rose by some 14 % year-on-ye...          2
9  The Stockmann department store will have a tot...          1

In [ ]:
# Focusing on seeing random samples from the finance dataset. 
import random
i = random.randint(0, len(finance_dataset)-10)
for row in finance_dataset[["Sentence", "Sentiment"]][i: i + 10].itertuples():
  print(row)
  print()

Pandas(Index=1128, Sentence='Tesla to recall 2,700 Model X SUVs over seat issue https://t.co/OdPraN59Xq $TSLA https://t.co/xvn4blIwpy https://t.co/ThfvWTnRPs', Sentiment=0)

Pandas(Index=1129, Sentence='Bovine slaughtering and cutting at the Kuopio facility will be transferred to the Kauhajoki slaughterhouse .', Sentiment=1)

Pandas(Index=1130, Sentence='`` Adjustment to the fall in price level , in contrast , has been less effective .', Sentiment=1)

Pandas(Index=1131, Sentence='Okmetic has a global customer base and sales network , production plants in Finland and the US and contract manufacturers in Japan and China .', Sentiment=1)

Pandas(Index=1132, Sentence='Public services will also be available .', Sentiment=1)

Pandas(Index=1133, Sentence='Asian traffic declined by 3.4 per cent .', Sentiment=1)

Pandas(Index=1134, Sentence='Finnish and Swedish construction markets are still experiencing an estimated 4 % annual growth in 2008 .', Sentiment=2)

Pandas(Index=1135, Sentence='Stock

In [ ]:
# Utilizing scikit learn to split the dataset into training and testing datasets 
from sklearn.model_selection import train_test_split

train_sentence, test_sentence, train_sentiment, test_sentiment  = train_test_split(finance_dataset["Sentence"].to_numpy(), finance_dataset["Sentiment"].to_numpy(), train_size = 0.8, random_state = 43)


In [ ]:
# Displaying the length of training and testing data, and the entire dataset.
print(f"Total sentences for training dataset: {len(train_sentence)}")
print(f"Total sentences for the test dataset: {len(test_sentence)}")
print(f"Total sentences in the whole dataset: {len(finance_dataset)}")

Total sentences for training dataset: 4673
Total sentences for the test dataset: 1169
Total sentences in the whole dataset: 5842


In [ ]:
train_sentence[:10] #looking at the first 10 sentences

array(['Operating profit rose to EUR 5mn from EUR 2.8 mn in the fourth quarter of 2008 .',
       'Earnings per share EPS are seen at EUR 0.56 , up from EUR 0.38 .',
       "`` P&O Ferries now has a very efficient and powerful vessel for its Dover to Calais route , '' head of the shipbuilder 's Rauma yard , Timo Suistio , said .",
       'The money will be spread mainly over 2011 and 2012 , the company said .',
       'StanChart and RBS struggle in Bank of England stress tests',
       'Upon establishment , the plan is directed to approximately 20 persons .',
       'At the moment , Valio is not worried , but if the ban continues for long , it may become quite a problem .',
       "Of the price , Kesko 's share is 10 mln euro $ 15.5 mln and it will recognize a gain of 4.0 mln euro $ 6.2 mln on the disposal which will be included in the result for the second quarter of 2008 .",
       '`` The additional flight linking Mumbai with Helsinki was dictated by the strong traffic demand betwee

In [ ]:
for i in train_sentence[0:10]: #splitting each token in the sentences on any whitespace
  print(i.split())


['Operating', 'profit', 'rose', 'to', 'EUR', '5mn', 'from', 'EUR', '2.8', 'mn', 'in', 'the', 'fourth', 'quarter', 'of', '2008', '.']
['Earnings', 'per', 'share', 'EPS', 'are', 'seen', 'at', 'EUR', '0.56', ',', 'up', 'from', 'EUR', '0.38', '.']
['``', 'P&O', 'Ferries', 'now', 'has', 'a', 'very', 'efficient', 'and', 'powerful', 'vessel', 'for', 'its', 'Dover', 'to', 'Calais', 'route', ',', "''", 'head', 'of', 'the', 'shipbuilder', "'s", 'Rauma', 'yard', ',', 'Timo', 'Suistio', ',', 'said', '.']
['The', 'money', 'will', 'be', 'spread', 'mainly', 'over', '2011', 'and', '2012', ',', 'the', 'company', 'said', '.']
['StanChart', 'and', 'RBS', 'struggle', 'in', 'Bank', 'of', 'England', 'stress', 'tests']
['Upon', 'establishment', ',', 'the', 'plan', 'is', 'directed', 'to', 'approximately', '20', 'persons', '.']
['At', 'the', 'moment', ',', 'Valio', 'is', 'not', 'worried', ',', 'but', 'if', 'the', 'ban', 'continues', 'for', 'long', ',', 'it', 'may', 'become', 'quite', 'a', 'problem', '.']
['Of'

In [ ]:
len(train_sentence)

4673

In [ ]:
# Total elements in training_sentence before splitting 
before_split = len(train_sentence)


# Total elements in training_sentence after splitting 
max_vocab = sum([len(i.split()) for i in train_sentence]) 

maximum_length = round(max_vocab/before_split)
maximum_length, max_vocab

(21, 98295)

In [ ]:
# Converting the text to numbers utilzing tokenization. 
import keras  
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.layers import Embedding 

vectorizer_layer = tf.keras.layers.TextVectorization (
    max_tokens = max_vocab, # max limit for unique words
    split="whitespace",
    ngrams = None,
    output_mode = "int", 
    output_sequence_length = maximum_length #how long the tokens can be
)

In [ ]:
vectorizer_layer.adapt(train_sentence) 


In [ ]:
embedding_layer  = tf.keras.layers.Embedding( #turns integers into dense vectors
  input_dim = max_vocab, 
  output_dim = 128,
  input_length = maximum_length
)
embedding_layer

In [ ]:
random_sentence = random.choice(train_sentence) #selects a random sentence from training dataset
sample_em = embedding_layer(vectorizer_layer([random_sentence]))
sample_em

<tf.Tensor: shape=(1, 21, 128), dtype=float32, numpy=
array([[[ 0.03117314, -0.01495209,  0.00897781, ..., -0.04304645,
          0.03142207,  0.0043871 ],
        [-0.03175236,  0.04613307, -0.03471109, ...,  0.00765523,
         -0.00497843, -0.03250787],
        [ 0.02315822, -0.02461975, -0.01570848, ..., -0.04123599,
         -0.02744631, -0.0168938 ],
        ...,
        [-0.02023824,  0.02285537,  0.0357717 , ...,  0.03797219,
         -0.03462192,  0.00265925],
        [ 0.0069899 ,  0.02350808,  0.00316936, ...,  0.04089225,
         -0.032547  , -0.02700019],
        [-0.04636655, -0.01549777,  0.00474722, ..., -0.01231077,
         -0.00083681, -0.0026543 ]]], dtype=float32)>

Baseline Model using Naives Bayes

In [ ]:
test_sentiment

array([1, 1, 2, ..., 1, 2, 1])

In [ ]:
train_sentence

array(['Operating profit rose to EUR 5mn from EUR 2.8 mn in the fourth quarter of 2008 .',
       'Earnings per share EPS are seen at EUR 0.56 , up from EUR 0.38 .',
       "`` P&O Ferries now has a very efficient and powerful vessel for its Dover to Calais route , '' head of the shipbuilder 's Rauma yard , Timo Suistio , said .",
       ...,
       'Paper companies were in negative territories , with Stora Enso R shedding 1.62 pct to 12.73 eur , UPM-Kymmene down 0.80 pct at 18.64 eur and M-real B 0.18 pct lower at 5.57 eur .',
       'The company plans to close two of the three lines at the plant , where some 450 jobs are under threat .',
       'Sales of mid-strength beer decreased by 40 % .'], dtype=object)

In [ ]:


from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer


baseline = Pipeline(
    [
     ("tfid", TfidfVectorizer()),  #extractor - extracting features 
     ("clf", MultinomialNB()),  # classifier - will classify the patterns 
    ])
baseline.fit(train_sentence, train_sentiment) #fitting on training dataset
baseline_pred = baseline.predict(test_sentence) #baseline will predict on testing data

baseline_pred[:500]

array([1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1,

In [ ]:
train_sentiment

array([2, 2, 2, ..., 0, 1, 0])

In [ ]:
test_sentiment.shape, baseline_pred.shape

((1169,), (1169,))

In [ ]:
from sklearn.metrics import recall_score, accuracy_score, f1_score, precision_score


# function that will display metrics 
def get_metrics(y_true, y_pred):
  accuracy_metric = accuracy_score(y_true, y_pred) #will get an accuracy score
  precession_metric = precision_score(y_true, y_pred, average = "weighted") 
  recall_metric = recall_score(y_true, y_pred, average = "weighted")
  f1_metric = f1_score(y_true, y_pred, average = "weighted")
   
  model_metrics = {"accuracy_score": accuracy_metric, "precession_score": precession_metric, "recall_score": recall_metric, "f1_score": f1_metric}
  return(model_metrics) # return a dictionary, that will have the values for the metric


In [ ]:
baseline_results = get_metrics(test_sentiment, baseline_pred) # will get results for the baseline
baseline_results

{'accuracy_score': 0.6518391787852865,
 'f1_score': 0.5790212756042808,
 'precession_score': 0.6778744031693452,
 'recall_score': 0.6518391787852865}

In [ ]:
from tensorflow.keras import layers
train_sentence.shape, test_sentence.shape, train_sentiment.shape, test_sentiment.shape

((4673,), (1169,), (4673,), (1169,))

First Model Based on only Dense Layers

In [ ]:
# Building a Model with only Dense Layers

tf.random.set_seed(47)
inputs = layers.Input(shape = (1, ) , dtype = "string")
x = vectorizer_layer(inputs)

x = embedding_layer(x)
x = tf.keras.layers.Dense(10, activation = "relu")(x)
x = layers.GlobalMaxPooling1D()(x)
outputs = layers.Dense(3, activation = "softmax")(x)

#groups layers into an object with training and inference features
first_model = tf.keras.Model(inputs = inputs, outputs = outputs) 


first_model.summary() # shows summary of the model


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 21)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 21, 128)           12581760  
                                                                 
 dense (Dense)               (None, 21, 10)            1290      
                                                                 
 global_max_pooling1d (Globa  (None, 10)               0         
 lMaxPooling1D)                                                  
                                                                 
 dense_1 (Dense)             (None, 3)                 33    

In [ ]:
first_model.compile(loss = "sparse_categorical_crossentropy", 
                    optimizer = "adam", metrics = ["accuracy"])

first_hist = first_model.fit(train_sentence, 
                            train_sentiment, epochs = 5, # model will displays results for 5 durations 
                            validation_data = (test_sentence, test_sentiment))

Epoch 1/5
147/147 [==============================] - 21s 131ms/step - loss: 0.9248 - accuracy: 0.5996 - val_loss: 0.8283 - val_accuracy: 0.6578
Epoch 2/5
147/147 [==============================] - 19s 129ms/step - loss: 0.7030 - accuracy: 0.7201 - val_loss: 0.7448 - val_accuracy: 0.6852
Epoch 3/5
147/147 [==============================] - 19s 126ms/step - loss: 0.5189 - accuracy: 0.7982 - val_loss: 0.7546 - val_accuracy: 0.6784
Epoch 4/5
147/147 [==============================] - 19s 132ms/step - loss: 0.3857 - accuracy: 0.8513 - val_loss: 0.8176 - val_accuracy: 0.6647
Epoch 5/5
147/147 [==============================] - 19s 127ms/step - loss: 0.3039 - accuracy: 0.8761 - val_loss: 0.8980 - val_accuracy: 0.6382


In [ ]:
import numpy as np  

first_model_pred = first_model.predict(test_sentence)
first_model_pred_round = tf.round(first_model_pred) #rounding the first predictions to either 0 or 1
first_model_pred_round

<tf.Tensor: shape=(1169, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)>

In [ ]:
                            # utilized argmax to find the index which has the largest value in each respective arrays
first_model_pred_classes = tf.argmax(first_model_pred_round, axis = 1)

first_model_pred_classes

<tf.Tensor: shape=(1169,), dtype=int64, numpy=array([1, 1, 2, ..., 1, 2, 1])>

In [ ]:
test_sentiment.shape

(1169,)

In [ ]:
first_model_results = get_metrics(y_true = test_sentiment, y_pred = first_model_pred_classes)
first_model_results

{'accuracy_score': 0.6330196749358425,
 'f1_score': 0.6382968748428446,
 'precession_score': 0.6454769812561617,
 'recall_score': 0.6330196749358425}

Model based on Recurrent Neural Network-LSTM

In [ ]:
tf.random.set_seed(47)
inputs = layers.Input(shape = (1, ) , dtype = "string")

x = vectorizer_layer(inputs) 


second_model_embedding = tf.keras.layers.Embedding(
    input_dim = max_vocab,
    output_dim = 128,
    input_length = maximum_length
)

x = second_model_embedding(x) 

# adding an LSTM layers
x = tf.keras.layers.LSTM(52, return_sequences = True)(x) #set return_sequence to True, to stack layers
x = tf.keras.layers.LSTM(52)(x)

outputs = layers.Dense(3, activation = "softmax")(x) 


second_model = tf.keras.Model(inputs = inputs, outputs = outputs)
second_model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 21)               0         
 torization)                                                     
                                                                 
 embedding_1 (Embedding)     (None, 21, 128)           12581760  
                                                                 
 lstm (LSTM)                 (None, 21, 52)            37648     
                                                                 
 lstm_1 (LSTM)               (None, 52)                21840     
                                                                 
 dense_2 (Dense)             (None, 3)                 159       
                                                           

In [ ]:
second_model.compile(loss = "sparse_categorical_crossentropy", 
                    optimizer = "adam", metrics = ["accuracy"])

second_hist = second_model.fit(train_sentence, 
                            train_sentiment, epochs = 5,
                            validation_data = (test_sentence, test_sentiment))

Epoch 1/5
147/147 [==============================] - 26s 155ms/step - loss: 0.8851 - accuracy: 0.6101 - val_loss: 0.7823 - val_accuracy: 0.6920
Epoch 2/5
147/147 [==============================] - 22s 148ms/step - loss: 0.5375 - accuracy: 0.7822 - val_loss: 0.7369 - val_accuracy: 0.6826
Epoch 3/5
147/147 [==============================] - 22s 148ms/step - loss: 0.2756 - accuracy: 0.8755 - val_loss: 0.8520 - val_accuracy: 0.6664
Epoch 4/5
147/147 [==============================] - 22s 149ms/step - loss: 0.1939 - accuracy: 0.8981 - val_loss: 0.9324 - val_accuracy: 0.6647
Epoch 5/5
147/147 [==============================] - 22s 152ms/step - loss: 0.1559 - accuracy: 0.9091 - val_loss: 1.3341 - val_accuracy: 0.6621


In [ ]:
second_model_pred = second_model.predict(test_sentence) #will predict on testing data
second_model_pred_round = tf.round(second_model_pred)
second_model_pred_classes = tf.argmax(second_model_pred_round, axis = 1)
second_model_pred_classes[:50] #will show the first 50 predictions 

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([1, 1, 2, 1, 2, 2, 0, 2, 1, 2, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1,
       2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 1, 2, 2, 1, 0, 2, 1, 1, 0, 1, 1, 1,
       0, 2, 1, 1, 2, 2])>

In [ ]:
second_model_results = get_metrics(y_true = test_sentiment, y_pred =second_model_pred_classes)
second_model_results

{'accuracy_score': 0.6621043627031651,
 'f1_score': 0.6544795851480242,
 'precession_score': 0.6484097043868638,
 'recall_score': 0.6621043627031651}

Based on Creating a Dataframe, and comparing the results of two models and the baseline. We can see that the second_model(RNN- LSTM) performs the best.

In [ ]:
total_results = pd.DataFrame({"baseline": baseline_results, 
              "first_model(simple dense layers)": first_model_results, 
              "second_model(RNN- LSTM)": second_model_results})
total_model_results = total_results.transpose()
total_model_results

accuracy_score  precession_score  \
baseline                                0.651839          0.677874   
first_model(simple dense layers)        0.633020          0.645477   
second_model(RNN- LSTM)                 0.662104          0.648410   

                                  recall_score  f1_score  
baseline                              0.651839  0.579021  
first_model(simple dense layers)      0.633020  0.638297  
second_model(RNN- LSTM)               0.662104  0.654480