<a href="https://colab.research.google.com/github/yashpokra/Financial-Sentiment-Analysis/blob/main/Financial_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import random 

In [ ]:
#Downloading dataset file from github
!wget https://raw.githubusercontent.com/yashpokra/Financial-Sentiment-Analysis/main/financial%20-%20sentiment%20analysis.csv


--2022-05-12 03:00:15--  https://raw.githubusercontent.com/yashpokra/Financial-Sentiment-Analysis/main/financial%20-%20sentiment%20analysis.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 745117 (728K) [text/plain]
Saving to: ‘financial - sentiment analysis.csv’

financial - sentime 100%[===================>] 727.65K  --.-KB/s    in 0.005s  

2022-05-12 03:00:16 (151 MB/s) - ‘financial - sentiment analysis.csv’ saved [745117/745117]



In [ ]:
# Creating a data frame 
finance_dataset = pd.read_csv("/content/financial - sentiment analysis.csv")

In [ ]:
finance_dataset.head(10) # checking the first 10 rows 

Sentence Sentiment
0  The GeoSolutions technology will leverage Bene...  positive
1  $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2  For the last quarter of 2010 , Componenta 's n...  positive
3  According to the Finnish-Russian Chamber of Co...   neutral
4  The Swedish buyout firm has sold its remaining...   neutral
5    $SPY wouldn't be surprised to see a green close  positive
6  Shell's $70 Billion BG Deal Meets Shareholder ...  negative
7  SSH COMMUNICATIONS SECURITY CORP STOCK EXCHANG...  negative
8  Kone 's net sales rose by some 14 % year-on-ye...  positive
9  The Stockmann department store will have a tot...   neutral

Converting the Sentiment labels into numerical form, so that we can develop a multiclass problem, where:

`negative` = 0

`neutral` = 1 

`positive` = 2


In [ ]:
dataset_dict = {"negative": 0, "neutral": 1, "positive":2} # Creating dictionary 
finance_dataset["Sentiment"].replace(dataset_dict, inplace = True) # set inplace to True, so that it will directly the modify the changes to the dataframe directly
finance_dataset.head(10)

Sentence  Sentiment
0  The GeoSolutions technology will leverage Bene...          2
1  $ESI on lows, down $1.50 to $2.50 BK a real po...          0
2  For the last quarter of 2010 , Componenta 's n...          2
3  According to the Finnish-Russian Chamber of Co...          1
4  The Swedish buyout firm has sold its remaining...          1
5    $SPY wouldn't be surprised to see a green close          2
6  Shell's $70 Billion BG Deal Meets Shareholder ...          0
7  SSH COMMUNICATIONS SECURITY CORP STOCK EXCHANG...          0
8  Kone 's net sales rose by some 14 % year-on-ye...          2
9  The Stockmann department store will have a tot...          1

In [ ]:
# Focusing on seeing random datasets from the finance dataset. 
import random
i = random.randint(0, len(finance_dataset)-10)
for row in finance_dataset[["Sentence", "Sentiment"]][i: i + 10].itertuples():
  print(row)
  print()

Pandas(Index=2593, Sentence="The Board of Directors proposes to the Shareholders ' Meeting on 18 March 2010 that the company would pay dividend for the financial year January 1 - December 31 , 2009 , EUR 0.02 per share .", Sentiment=1)

Pandas(Index=2594, Sentence='RBS chairman admits surprise at size of regulatory penalties', Sentiment=0)

Pandas(Index=2595, Sentence='Ramirent Finland is the domestic unit of machinery rental company Ramirent Oyj HEL : RMR1V .', Sentiment=1)

Pandas(Index=2596, Sentence='Like all other mechanical pipettors from Biohit , also Proline Plus is CE-IVD marked and comes with a 3-year warranty .', Sentiment=1)

Pandas(Index=2597, Sentence="Earlier today , Geberit 's Finnish rival Uponor OYJ cut its full-year sales growth forecast to 6 pct from 10 pct , blaming tough conditions in Germany and the US , as well as currency factors .", Sentiment=1)

Pandas(Index=2598, Sentence='The invention carries International Patent Publication No. .', Sentiment=1)

Pandas(In

In [ ]:
# Utilizing scikit learn to split the dataset into training and testing datasets 
from sklearn.model_selection import train_test_split

train_sentence, test_sentence, train_sentiment, test_sentiment  = train_test_split(finance_dataset["Sentence"].to_numpy(), finance_dataset["Sentiment"].to_numpy(), train_size = 0.8, random_state = 43)
len(train_sentence)


4673

In [ ]:
# Splitting training data into validation data
train_sentence, validation_sentence, train_sentiment, val_sentiment = train_test_split(finance_dataset["Sentence"].to_numpy(), finance_dataset["Sentiment"].to_numpy(), test_size = 0.1, random_state = 43)

print(f"Total sentences for training dataset: {len(train_sentence)}")
print(f"Total sentences for the validation dataset: {len(validation_sentence)}")
print(f"Total sentences for test dataset: {len(test_sentence)}")
print(f"Total sentences in the whole dataset: {len(finance_dataset)}")




Total sentences for training dataset: 5257
Total sentences for the validation dataset: 585
Total sentences for test dataset: 1169
Total sentences in the whole dataset: 5842


In [ ]:
train_sentence[:10]

array(["Elcoteq 's global service offering covers the entire lifecycle of products , from product development to after-market services .",
       'The inventors are Mukkavilli Krishna Kiran , Sabharwal Ashutosh and Aazhang Behnaam .',
       'The group posted net sales of 35.3 mln euro $ 46.5 mln and an operating profit of 760,000 euro $ 1.0 mln in 2005 .',
       'Delivery is expected to take place later this month .',
       'Both operating profit and net sales for the six-month period increased , respectively , from EUR13 .8 m and EUR143 .6 m , as compared to the corresponding period in 2007 .',
       '$BAC $ADSK $NFLX long this morning',
       'Mercator will use the software for its logistic , retail and wholesale operations in Slovenia and its other markets in southeastern Europe .',
       "South African Sappi will become the largest foreign forest industry company operating in Finland as a result of the acquisition Finnish M-real Corporation 's Graphic Papers Business unit .",

In [ ]:
for i in train_sentence[0:10]:
  print(i.split())


['Elcoteq', "'s", 'global', 'service', 'offering', 'covers', 'the', 'entire', 'lifecycle', 'of', 'products', ',', 'from', 'product', 'development', 'to', 'after-market', 'services', '.']
['The', 'inventors', 'are', 'Mukkavilli', 'Krishna', 'Kiran', ',', 'Sabharwal', 'Ashutosh', 'and', 'Aazhang', 'Behnaam', '.']
['The', 'group', 'posted', 'net', 'sales', 'of', '35.3', 'mln', 'euro', '$', '46.5', 'mln', 'and', 'an', 'operating', 'profit', 'of', '760,000', 'euro', '$', '1.0', 'mln', 'in', '2005', '.']
['Delivery', 'is', 'expected', 'to', 'take', 'place', 'later', 'this', 'month', '.']
['Both', 'operating', 'profit', 'and', 'net', 'sales', 'for', 'the', 'six-month', 'period', 'increased', ',', 'respectively', ',', 'from', 'EUR13', '.8', 'm', 'and', 'EUR143', '.6', 'm', ',', 'as', 'compared', 'to', 'the', 'corresponding', 'period', 'in', '2007', '.']
['$BAC', '$ADSK', '$NFLX', 'long', 'this', 'morning']
['Mercator', 'will', 'use', 'the', 'software', 'for', 'its', 'logistic', ',', 'retail', 

In [ ]:
len(train_sentence)

5257

In [ ]:
# Total elements in training_sentence before splitting 
before_split = len(train_sentence)


# Total elements in training_sentence after splitting 
max_vocab = sum([len(i.split()) for i in train_sentence]) 

maximum_length = round(max_vocab/before_split)
maximum_length, max_vocab

(21, 110829)

In [ ]:
# Converting the text to numbers utilzing tokenization. 
import keras  
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.layers import Embedding 

vectorizer_layer = tf.keras.layers.TextVectorization (
    max_tokens = max_vocab, # max limit for unique words
    split="whitespace",
    ngrams = None,
    output_mode = "int", 
    output_sequence_length = maximum_length
)


In [ ]:
vectorizer_layer.adapt(train_sentence) 


In [ ]:
embedding_layer  = tf.keras.layers.Embedding(
  input_dim = max_vocab, 
  output_dim = 128,
  input_length = maximum_length
)
embedding_layer

In [ ]:
random_sentence = random.choice(train_sentence)
sample_em = embedding_layer(vectorizer_layer([random_sentence]))
sample_em

<tf.Tensor: shape=(1, 21, 128), dtype=float32, numpy=
array([[[-0.0325613 ,  0.03857769, -0.01384035, ...,  0.03748462,
         -0.03352014, -0.02825221],
        [-0.03982903,  0.01831805, -0.0169531 , ...,  0.00642641,
         -0.00711645, -0.03672038],
        [-0.00190771,  0.02690012,  0.04577408, ...,  0.0015307 ,
         -0.00563933, -0.03532264],
        ...,
        [-0.0007658 , -0.03120708,  0.000804  , ..., -0.04641673,
          0.01989922, -0.01390143],
        [-0.0007658 , -0.03120708,  0.000804  , ..., -0.04641673,
          0.01989922, -0.01390143],
        [-0.0007658 , -0.03120708,  0.000804  , ..., -0.04641673,
          0.01989922, -0.01390143]]], dtype=float32)>

Baseline Model using Naives Bayes

In [ ]:
val_sentiment

array([1, 1, 2, 0, 2, 2, 1, 2, 1, 2, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 1, 1,
       2, 1, 0, 1, 1, 0, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 0, 1,
       1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 0, 2, 1, 2, 1,
       0, 1, 2, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2,
       1, 0, 1, 1, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 1, 1, 2, 1, 2, 0, 2,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 1, 1, 1, 1, 0,
       2, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2, 1,
       2, 1, 0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2,
       2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 0, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 1, 2,
       0, 1, 1, 0, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1,
       0, 2, 0, 0, 2, 0, 1, 0, 0, 2, 1, 1, 2, 0, 1,

In [ ]:
train_sentence

array(["Elcoteq 's global service offering covers the entire lifecycle of products , from product development to after-market services .",
       'The inventors are Mukkavilli Krishna Kiran , Sabharwal Ashutosh and Aazhang Behnaam .',
       'The group posted net sales of 35.3 mln euro $ 46.5 mln and an operating profit of 760,000 euro $ 1.0 mln in 2005 .',
       ...,
       'Paper companies were in negative territories , with Stora Enso R shedding 1.62 pct to 12.73 eur , UPM-Kymmene down 0.80 pct at 18.64 eur and M-real B 0.18 pct lower at 5.57 eur .',
       'The company plans to close two of the three lines at the plant , where some 450 jobs are under threat .',
       'Sales of mid-strength beer decreased by 40 % .'], dtype=object)

In [ ]:

from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer


baseline = Pipeline(
    [
     ("tfid", TfidfVectorizer()),  #extractor - extracting features 
     ("clf", MultinomialNB()),  # classifier - will classify the patterns 
    ])
baseline.fit(train_sentence, train_sentiment)
baseline_pred = baseline.predict(validation_sentence)

baseline_pred

array([1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1,

In [ ]:
train_sentiment

array([1, 1, 1, ..., 0, 1, 0])

In [ ]:
val_sentiment.shape, baseline_pred.shape

((585,), (585,))

In [ ]:
from sklearn.metrics import recall_score, accuracy_score, f1_score, precision_score

def get_metrics(y_true, y_pred):
  accuracy_metric = accuracy_score(y_true, y_pred)
  precession_metric = precision_score(y_true, y_pred, average = "weighted") 
  recall_metric = recall_score(y_true, y_pred, average = "weighted")
  f1_metric = f1_score(y_true, y_pred, average = "weighted")
   
  model_metrics = {"accuracy_score": accuracy_metric, "precession_score": precession_metric, "recall_score": recall_metric, "f1_score": f1_metric}
  return(model_metrics)


In [ ]:
baseline_results = get_metrics(val_sentiment, baseline_pred)
baseline_results

{'accuracy_score': 0.6512820512820513,
 'f1_score': 0.5811778710568056,
 'precession_score': 0.6511610200596359,
 'recall_score': 0.6512820512820513}

In [ ]:
train_sentence.shape

(5257,)

In [ ]:
from tensorflow.keras import layers
train_sentence
train_sentence.shape, validation_sentence.shape, train_sentiment.shape, val_sentiment.shape

((5257,), (585,), (5257,), (585,))

Model 1: Simple Dense Layers

In [ ]:
tf.random.set_seed(47)
inputs = layers.Input(shape = (1, ) , dtype = "string")
x = vectorizer_layer(inputs)
# print(x.shape)
x = embedding_layer(x)
x = tf.keras.layers.Dense(10, activation = "relu")(x)
x = layers.GlobalMaxPooling1D()(x)
outputs = layers.Dense(3, activation = "softmax")(x)
# print(outputs.shape)
first_model = tf.keras.Model(inputs = inputs, outputs = outputs)
first_model.summary()



Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 21)               0         
 torization)                                                     
                                                                 
 embedding (Embedding)       (None, 21, 128)           14186112  
                                                                 
 dense (Dense)               (None, 21, 10)            1290      
                                                                 
 global_max_pooling1d (Globa  (None, 10)               0         
 lMaxPooling1D)                                                  
                                                                 
 dense_1 (Dense)             (None, 3)                 33    

In [ ]:
first_model.compile(loss = "sparse_categorical_crossentropy", 
                    optimizer = "adam", metrics = ["accuracy"])

first_hist = first_model.fit(train_sentence, 
                            train_sentiment, epochs = 5,
                            validation_data = (validation_sentence, val_sentiment))


Epoch 1/5
165/165 [==============================] - 7s 12ms/step - loss: 0.9248 - accuracy: 0.5929 - val_loss: 0.8165 - val_accuracy: 0.6615
Epoch 2/5
165/165 [==============================] - 2s 11ms/step - loss: 0.6952 - accuracy: 0.7295 - val_loss: 0.7288 - val_accuracy: 0.6667
Epoch 3/5
165/165 [==============================] - 2s 11ms/step - loss: 0.5208 - accuracy: 0.7875 - val_loss: 0.7486 - val_accuracy: 0.6615
Epoch 4/5
165/165 [==============================] - 2s 11ms/step - loss: 0.3957 - accuracy: 0.8421 - val_loss: 0.8090 - val_accuracy: 0.6496
Epoch 5/5
165/165 [==============================] - 2s 11ms/step - loss: 0.3166 - accuracy: 0.8636 - val_loss: 0.8949 - val_accuracy: 0.6308


In [ ]:
import numpy as np

first_model_pred = first_model.predict(validation_sentence)
first_model_pred_round = tf.round(first_model_pred)
first_model_pred_round

<tf.Tensor: shape=(585, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
#using tf.argmax to get the largest values along the axis of the tensor

first_model_pred_classes = tf.argmax(first_model_pred_round, axis = 1)

first_model_pred_classes

<tf.Tensor: shape=(585,), dtype=int64, numpy=
array([1, 1, 0, 1, 2, 2, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 2, 1, 1, 1, 0, 2, 1, 1, 2, 2, 1, 0, 2, 1, 1, 0, 0, 0, 1,
       0, 2, 1, 1, 0, 2, 2, 1, 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 2, 0,
       1, 1, 2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2,
       1, 0, 1, 1, 1, 2, 1, 0, 2, 1, 2, 1, 1, 0, 1, 0, 2, 1, 1, 0, 1, 0,
       2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 0, 1, 0, 1, 2, 1,
       2, 1, 1, 2, 1, 0, 1, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0,
       1, 1, 2, 2, 2, 0, 2, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0,
     

In [ ]:
val_sentiment

array([1, 1, 2, 0, 2, 2, 1, 2, 1, 2, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 1, 1,
       2, 1, 0, 1, 1, 0, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 0, 1,
       1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 0, 2, 1, 2, 1,
       0, 1, 2, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2,
       1, 0, 1, 1, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 1, 1, 2, 1, 2, 0, 2,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 1, 1, 1, 1, 0,
       2, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2, 1,
       2, 1, 0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2,
       2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 2, 0, 1, 1, 1, 2, 0, 2, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 0, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 1, 2,
       0, 1, 1, 0, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1,
       0, 2, 0, 0, 2, 0, 1, 0, 0, 2, 1, 1, 2, 0, 1,

In [ ]:
first_model_results = get_metrics(y_true = val_sentiment, y_pred = first_model_pred_classes)
first_model_results

{'accuracy_score': 0.6341880341880342,
 'f1_score': 0.635478466392317,
 'precession_score': 0.6375725220071585,
 'recall_score': 0.6341880341880342}

Reccurent Neural Networks

In [ ]:
tf.random.set_seed(47)
inputs = layers.Input(shape = (1, ) , dtype = "string")

x = vectorizer_layer(inputs)

second_model_embedding = tf.keras.layers.Embedding(
    input_dim = max_vocab,
    output_dim = 128,
    input_length = maximum_length
)

x = second_model_embedding(x)


x = tf.keras.layers.LSTM(52, return_sequences = True)(x)
x = tf.keras.layers.LSTM(52)(x)

outputs = layers.Dense(3, activation = "softmax")(x)


second_model = tf.keras.Model(inputs = inputs, outputs = outputs)
second_model.summary()


Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization (TextVec  (None, 21)               0         
 torization)                                                     
                                                                 
 embedding_1 (Embedding)     (None, 21, 128)           14186112  
                                                                 
 lstm (LSTM)                 (None, 21, 52)            37648     
                                                                 
 lstm_1 (LSTM)               (None, 52)                21840     
                                                                 
 dense_2 (Dense)             (None, 3)                 159       
                                                           

In [ ]:
#compiling the model

second_model.compile(loss = "sparse_categorical_crossentropy", 
                    optimizer = "adam", metrics = ["accuracy"])

second_hist = second_model.fit(train_sentence, 
                            train_sentiment, epochs = 5,
                            validation_data = (validation_sentence, val_sentiment))

Epoch 1/5
165/165 [==============================] - 8s 18ms/step - loss: 0.8697 - accuracy: 0.6213 - val_loss: 0.7311 - val_accuracy: 0.7094
Epoch 2/5
165/165 [==============================] - 2s 14ms/step - loss: 0.4922 - accuracy: 0.7930 - val_loss: 0.7314 - val_accuracy: 0.6872
Epoch 3/5
165/165 [==============================] - 2s 14ms/step - loss: 0.2647 - accuracy: 0.8701 - val_loss: 1.0191 - val_accuracy: 0.6752
Epoch 4/5
165/165 [==============================] - 2s 15ms/step - loss: 0.1938 - accuracy: 0.8912 - val_loss: 1.2004 - val_accuracy: 0.6701
Epoch 5/5
165/165 [==============================] - 2s 14ms/step - loss: 0.1514 - accuracy: 0.9039 - val_loss: 1.4144 - val_accuracy: 0.6906


In [ ]:
second_model_pred = second_model.predict(validation_sentence)
second_model_pred_round = tf.round(second_model_pred)
second_model_pred_classes = tf.argmax(second_model_pred_round, axis = 1)
second_model_pred_classes[:50]

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 0, 1, 2, 2, 1, 1, 1, 1,
       2, 1, 2, 2, 1, 2, 1, 0, 2, 1, 1, 2, 2, 1, 0, 2, 1, 1, 1, 0, 2, 1,
       1, 2, 1, 1, 1, 2])>

In [ ]:
second_model_results = get_metrics(y_true = val_sentiment, y_pred =second_model_pred_classes)
second_model_results

{'accuracy_score': 0.694017094017094,
 'f1_score': 0.6831083713352083,
 'precession_score': 0.6762557801920915,
 'recall_score': 0.694017094017094}

Based on Creating a Dataframe, and comparing the results of two models and the baseline. We can see that the second_model(RNN- LSTM) performs the best. 

In [ ]:
total_results = pd.DataFrame({"baseline": baseline_results,  # will create a DataFrame based on the results of the models and the baseline
              "first_model(simple dense layers)": first_model_results,  
              "second_model(RNN- LSTM)": second_model_results})
total_model_results = total_results.transpose()
total_model_results

accuracy_score  precession_score  \
baseline                                0.651282          0.651161   
first_model(simple dense layers)        0.634188          0.637573   
second_model(RNN- LSTM)                 0.694017          0.676256   

                                  recall_score  f1_score  
baseline                              0.651282  0.581178  
first_model(simple dense layers)      0.634188  0.635478  
second_model(RNN- LSTM)               0.694017  0.683108